name: MoveNow
options:
  bundleIdPrefix: com.melodicdev
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
targets:
  MoveNow:
    type: application
    platform: macOS
    sources:
      - path: MoveNow
        excludes:
          - Info.plist
          - MoveNow.entitlements
    settings:
      base:
        INFOPLIST_FILE: MoveNow/Info.plist
        CODE_SIGN_ENTITLEMENTS: MoveNow/MoveNow.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.melodicdev.movenow
        PRODUCT_NAME: Move Now
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: "YES"
